/* ============================================================================
   Every city and municipality in Romania — 320 of them — for the city picker
   on /niches.

   Names carry their proper diacritics (comma-below ș and ț, not the cedilla
   forms some datasets ship). Built by joining the `romanian-cities` package's
   list of cities and municipalities, which is the right granularity here
   (communes and villages are not markets we sell a position in), against the
   diacritic spellings in github.com/catalin87/baza-de-date-localitati-romania,
   with five names fixed by hand where the join could not match them: Piatra
   Neamț, Roșiorii de Vede, Lehliu Gară, Slănic Moldova and Miercurea Ciuc.

   Counties are written out here rather than taken from either dataset: both
   ship them without diacritics, and there are only 42.

   GENERATED. Add a city by hand if one is missing, but do not reformat.
   ========================================================================= */

export type RoCity = {
  /** diacritic-free slug, used as the select value */
  id: string;
  city: string;
  county: string;
};

export const roCities: RoCity[] = [
  { id: "abrud", city: "Abrud", county: "Alba" },
  { id: "adjud", city: "Adjud", county: "Vrancea" },
  { id: "agnita", city: "Agnita", county: "Sibiu" },
  { id: "aiud", city: "Aiud", county: "Alba" },
  { id: "alba-iulia", city: "Alba Iulia", county: "Alba" },
  { id: "alexandria", city: "Alexandria", county: "Teleorman" },
  { id: "alesd", city: "Aleșd", county: "Bihor" },
  { id: "amara", city: "Amara", county: "Ialomița" },
  { id: "anina", city: "Anina", county: "Caraș-Severin" },
  { id: "aninoasa", city: "Aninoasa", county: "Hunedoara" },
  { id: "arad", city: "Arad", county: "Arad" },
  { id: "ardud", city: "Ardud", county: "Satu Mare" },
  { id: "avrig", city: "Avrig", county: "Sibiu" },
  { id: "azuga", city: "Azuga", county: "Prahova" },
  { id: "babadag", city: "Babadag", county: "Tulcea" },
  { id: "bacau", city: "Bacău", county: "Bacău" },
  { id: "baia-mare", city: "Baia Mare", county: "Maramureș" },
  { id: "baia-sprie", city: "Baia Sprie", county: "Maramureș" },
  { id: "baia-de-arama", city: "Baia de Aramă", county: "Mehedinți" },
  { id: "baia-de-aries", city: "Baia de Arieș", county: "Alba" },
  { id: "bals", city: "Balș", county: "Olt" },
  { id: "baraolt", city: "Baraolt", county: "Covasna" },
  { id: "bechet", city: "Bechet", county: "Dolj" },
  { id: "beclean", city: "Beclean", county: "Bistrița-Năsăud" },
  { id: "beius", city: "Beiuș", county: "Bihor" },
  { id: "berbesti", city: "Berbești", county: "Vâlcea" },
  { id: "beresti", city: "Berești", county: "Galați" },
  { id: "bicaz", city: "Bicaz", county: "Neamț" },
  { id: "bistrita", city: "Bistrița", county: "Bistrița-Năsăud" },
  { id: "blaj", city: "Blaj", county: "Alba" },
  { id: "bocsa", city: "Bocșa", county: "Caraș-Severin" },
  { id: "boldesti-scaeni", city: "Boldești-Scăeni", county: "Prahova" },
  { id: "bolintin-vale", city: "Bolintin-Vale", county: "Giurgiu" },
  { id: "borsec", city: "Borsec", county: "Harghita" },
  { id: "borsa", city: "Borșa", county: "Maramureș" },
  { id: "botosani", city: "Botoșani", county: "Botoșani" },
  { id: "brad", city: "Brad", county: "Hunedoara" },
  { id: "bragadiru", city: "Bragadiru", county: "Ilfov" },
  { id: "brasov", city: "Brașov", county: "Brașov" },
  { id: "breaza", city: "Breaza", county: "Prahova" },
  { id: "brezoi", city: "Brezoi", county: "Vâlcea" },
  { id: "brosteni", city: "Broșteni", county: "Suceava" },
  { id: "braila", city: "Brăila", county: "Brăila" },
  { id: "bucecea", city: "Bucecea", county: "Botoșani" },
  { id: "bucuresti", city: "București", county: "București" },
  { id: "budesti", city: "Budești", county: "Călărași" },
  { id: "buftea", city: "Buftea", county: "Ilfov" },
  { id: "buhusi", city: "Buhuși", county: "Bacău" },
  { id: "bumbesti-jiu", city: "Bumbești-Jiu", county: "Gorj" },
  { id: "buzias", city: "Buziaș", county: "Timiș" },
  { id: "buzau", city: "Buzău", county: "Buzău" },
  { id: "busteni", city: "Bușteni", county: "Prahova" },
  { id: "barlad", city: "Bârlad", county: "Vaslui" },
  { id: "babeni", city: "Băbeni", county: "Vâlcea" },
  { id: "baicoi", city: "Băicoi", county: "Prahova" },
  { id: "baile-govora", city: "Băile Govora", county: "Vâlcea" },
  { id: "baile-herculane", city: "Băile Herculane", county: "Caraș-Severin" },
  { id: "baile-olanesti", city: "Băile Olănești", county: "Vâlcea" },
  { id: "baile-tusnad", city: "Băile Tușnad", county: "Harghita" },
  { id: "bailesti", city: "Băilești", county: "Dolj" },
  { id: "balan", city: "Bălan", county: "Harghita" },
  { id: "balcesti", city: "Bălcești", county: "Vâlcea" },
  { id: "baneasa", city: "Băneasa", county: "Constanța" },
  { id: "cajvana", city: "Cajvana", county: "Suceava" },
  { id: "calafat", city: "Calafat", county: "Dolj" },
  { id: "caracal", city: "Caracal", county: "Olt" },
  { id: "caransebes", city: "Caransebeș", county: "Caraș-Severin" },
  { id: "carei", city: "Carei", county: "Satu Mare" },
  { id: "cavnic", city: "Cavnic", county: "Maramureș" },
  { id: "cehu-silvaniei", city: "Cehu Silvaniei", county: "Sălaj" },
  { id: "cernavoda", city: "Cernavodă", county: "Constanța" },
  { id: "chitila", city: "Chitila", county: "Ilfov" },
  { id: "chisineu-cris", city: "Chișineu-Criș", county: "Arad" },
  { id: "ciacova", city: "Ciacova", county: "Timiș" },
  { id: "cisnadie", city: "Cisnădie", county: "Sibiu" },
  { id: "cluj-napoca", city: "Cluj-Napoca", county: "Cluj" },
  { id: "codlea", city: "Codlea", county: "Brașov" },
  { id: "comarnic", city: "Comarnic", county: "Prahova" },
  { id: "comanesti", city: "Comănești", county: "Bacău" },
  { id: "constanta", city: "Constanța", county: "Constanța" },
  { id: "copsa-mica", city: "Copșa Mică", county: "Sibiu" },
  { id: "corabia", city: "Corabia", county: "Olt" },
  { id: "costesti", city: "Costești", county: "Argeș" },
  { id: "covasna", city: "Covasna", county: "Covasna" },
  { id: "craiova", city: "Craiova", county: "Dolj" },
  { id: "cristuru-secuiesc", city: "Cristuru Secuiesc", county: "Harghita" },
  { id: "cugir", city: "Cugir", county: "Alba" },
  { id: "curtea-de-arges", city: "Curtea de Argeș", county: "Argeș" },
  { id: "curtici", city: "Curtici", county: "Arad" },
  { id: "campeni", city: "Câmpeni", county: "Alba" },
  { id: "campia-turzii", city: "Câmpia Turzii", county: "Cluj" },
  { id: "campina", city: "Câmpina", county: "Prahova" },
  { id: "campulung", city: "Câmpulung", county: "Argeș" },
  { id: "campulung-moldovenesc", city: "Câmpulung Moldovenesc", county: "Suceava" },
  { id: "calan", city: "Călan", county: "Hunedoara" },
  { id: "calimanesti", city: "Călimănești", county: "Vâlcea" },
  { id: "calarasi", city: "Călărași", county: "Călărași" },
  { id: "cazanesti", city: "Căzănești", county: "Ialomița" },
  { id: "darabani", city: "Darabani", county: "Botoșani" },
  { id: "dej", city: "Dej", county: "Cluj" },
  { id: "deta", city: "Deta", county: "Timiș" },
  { id: "deva", city: "Deva", county: "Hunedoara" },
  { id: "dolhasca", city: "Dolhasca", county: "Suceava" },
  { id: "dorohoi", city: "Dorohoi", county: "Botoșani" },
  { id: "dragomiresti", city: "Dragomirești", county: "Maramureș" },
  { id: "drobeta-turnu-severin", city: "Drobeta-Turnu Severin", county: "Mehedinți" },
  { id: "draganesti-olt", city: "Drăgănești-Olt", county: "Olt" },
  { id: "dragasani", city: "Drăgășani", county: "Vâlcea" },
  { id: "dumbraveni", city: "Dumbrăveni", county: "Sibiu" },
  { id: "dabuleni", city: "Dăbuleni", county: "Dolj" },
  { id: "darmanesti", city: "Dărmănești", county: "Bacău" },
  { id: "eforie", city: "Eforie", county: "Constanța" },
  { id: "fetesti", city: "Fetești", county: "Ialomița" },
  { id: "fieni", city: "Fieni", county: "Dâmbovița" },
  { id: "fierbinti-targ", city: "Fierbinți-Târg", county: "Ialomița" },
  { id: "filiasi", city: "Filiași", county: "Dolj" },
  { id: "flamanzi", city: "Flămânzi", county: "Botoșani" },
  { id: "focsani", city: "Focșani", county: "Vrancea" },
  { id: "frasin", city: "Frasin", county: "Suceava" },
  { id: "fundulea", city: "Fundulea", county: "Călărași" },
  { id: "faget", city: "Făget", county: "Timiș" },
  { id: "fagaras", city: "Făgăraș", county: "Brașov" },
  { id: "falticeni", city: "Fălticeni", county: "Suceava" },
  { id: "faurei", city: "Făurei", county: "Brăila" },
  { id: "galati", city: "Galați", county: "Galați" },
  { id: "geoagiu", city: "Geoagiu", county: "Hunedoara" },
  { id: "gheorgheni", city: "Gheorgheni", county: "Harghita" },
  { id: "gherla", city: "Gherla", county: "Cluj" },
  { id: "ghimbav", city: "Ghimbav", county: "Brașov" },
  { id: "giurgiu", city: "Giurgiu", county: "Giurgiu" },
  { id: "gura-humorului", city: "Gura Humorului", county: "Suceava" },
  { id: "gaesti", city: "Găești", county: "Dâmbovița" },
  { id: "gataia", city: "Gătaia", county: "Timiș" },
  { id: "hateg", city: "Hațeg", county: "Hunedoara" },
  { id: "horezu", city: "Horezu", county: "Vâlcea" },
  { id: "huedin", city: "Huedin", county: "Cluj" },
  { id: "hunedoara", city: "Hunedoara", county: "Hunedoara" },
  { id: "husi", city: "Huși", county: "Vaslui" },
  { id: "harlau", city: "Hârlău", county: "Iași" },
  { id: "harsova", city: "Hârșova", county: "Constanța" },
  { id: "ianca", city: "Ianca", county: "Brăila" },
  { id: "iasi", city: "Iași", county: "Iași" },
  { id: "iernut", city: "Iernut", county: "Mureș" },
  { id: "ineu", city: "Ineu", county: "Arad" },
  { id: "isaccea", city: "Isaccea", county: "Tulcea" },
  { id: "jibou", city: "Jibou", county: "Sălaj" },
  { id: "jimbolia", city: "Jimbolia", county: "Timiș" },
  { id: "lehliu-gara", city: "Lehliu Gară", county: "Călărași" },
  { id: "lipova", city: "Lipova", county: "Arad" },
  { id: "liteni", city: "Liteni", county: "Suceava" },
  { id: "livada", city: "Livada", county: "Satu Mare" },
  { id: "ludus", city: "Luduș", county: "Mureș" },
  { id: "lugoj", city: "Lugoj", county: "Timiș" },
  { id: "lupeni", city: "Lupeni", county: "Hunedoara" },
  { id: "mangalia", city: "Mangalia", county: "Constanța" },
  { id: "marghita", city: "Marghita", county: "Bihor" },
  { id: "medgidia", city: "Medgidia", county: "Constanța" },
  { id: "medias", city: "Mediaș", county: "Sibiu" },
  { id: "miercurea-ciuc", city: "Miercurea Ciuc", county: "Harghita" },
  { id: "miercurea-nirajului", city: "Miercurea Nirajului", county: "Mureș" },
  { id: "miercurea-sibiului", city: "Miercurea Sibiului", county: "Sibiu" },
  { id: "mihailesti", city: "Mihăilești", county: "Giurgiu" },
  { id: "milisauti", city: "Milișăuți", county: "Suceava" },
  { id: "mioveni", city: "Mioveni", county: "Argeș" },
  { id: "mizil", city: "Mizil", county: "Prahova" },
  { id: "moinesti", city: "Moinești", county: "Bacău" },
  { id: "moldova-noua", city: "Moldova Nouă", county: "Caraș-Severin" },
  { id: "moreni", city: "Moreni", county: "Dâmbovița" },
  { id: "motru", city: "Motru", county: "Gorj" },
  { id: "murfatlar", city: "Murfatlar", county: "Constanța" },
  { id: "murgeni", city: "Murgeni", county: "Vaslui" },
  { id: "macin", city: "Măcin", county: "Tulcea" },
  { id: "magurele", city: "Măgurele", county: "Ilfov" },
  { id: "marasesti", city: "Mărășești", county: "Vrancea" },
  { id: "negresti", city: "Negrești", county: "Vaslui" },
  { id: "negresti-oas", city: "Negrești-Oaș", county: "Satu Mare" },
  { id: "negru-voda", city: "Negru Vodă", county: "Constanța" },
  { id: "nehoiu", city: "Nehoiu", county: "Buzău" },
  { id: "novaci", city: "Novaci", county: "Gorj" },
  { id: "nucet", city: "Nucet", county: "Bihor" },
  { id: "nadlac", city: "Nădlac", county: "Arad" },
  { id: "nasaud", city: "Năsăud", county: "Bistrița-Năsăud" },
  { id: "navodari", city: "Năvodari", county: "Constanța" },
  { id: "ocna-mures", city: "Ocna Mureș", county: "Alba" },
  { id: "ocna-sibiului", city: "Ocna Sibiului", county: "Sibiu" },
  { id: "ocnele-mari", city: "Ocnele Mari", county: "Vâlcea" },
  { id: "odobesti", city: "Odobești", county: "Vrancea" },
  { id: "odorheiu-secuiesc", city: "Odorheiu Secuiesc", county: "Harghita" },
  { id: "oltenita", city: "Oltenița", county: "Călărași" },
  { id: "onesti", city: "Onești", county: "Bacău" },
  { id: "oradea", city: "Oradea", county: "Bihor" },
  { id: "oravita", city: "Oravița", county: "Caraș-Severin" },
  { id: "orastie", city: "Orăștie", county: "Hunedoara" },
  { id: "orsova", city: "Orșova", county: "Mehedinți" },
  { id: "otopeni", city: "Otopeni", county: "Ilfov" },
  { id: "ovidiu", city: "Ovidiu", county: "Constanța" },
  { id: "otelu-rosu", city: "Oțelu Roșu", county: "Caraș-Severin" },
  { id: "panciu", city: "Panciu", county: "Vrancea" },
  { id: "pantelimon", city: "Pantelimon", county: "Ilfov" },
  { id: "pascani", city: "Pașcani", county: "Iași" },
  { id: "pecica", city: "Pecica", county: "Arad" },
  { id: "petrila", city: "Petrila", county: "Hunedoara" },
  { id: "petrosani", city: "Petroșani", county: "Hunedoara" },
  { id: "piatra-neamt", city: "Piatra Neamț", county: "Neamț" },
  { id: "piatra-olt", city: "Piatra-Olt", county: "Olt" },
  { id: "pitesti", city: "Pitești", county: "Argeș" },
  { id: "ploiesti", city: "Ploiești", county: "Prahova" },
  { id: "plopeni", city: "Plopeni", county: "Prahova" },
  { id: "podu-iloaiei", city: "Podu Iloaiei", county: "Iași" },
  { id: "pogoanele", city: "Pogoanele", county: "Buzău" },
  { id: "popesti-leordeni", city: "Popești-Leordeni", county: "Ilfov" },
  { id: "potcoava", city: "Potcoava", county: "Olt" },
  { id: "predeal", city: "Predeal", county: "Brașov" },
  { id: "pucioasa", city: "Pucioasa", county: "Dâmbovița" },
  { id: "pancota", city: "Pâncota", county: "Arad" },
  { id: "patarlagele", city: "Pătârlagele", county: "Buzău" },
  { id: "recas", city: "Recaș", county: "Timiș" },
  { id: "reghin", city: "Reghin", county: "Mureș" },
  { id: "resita", city: "Reșița", county: "Caraș-Severin" },
  { id: "roman", city: "Roman", county: "Neamț" },
  { id: "rovinari", city: "Rovinari", county: "Gorj" },
  { id: "roznov", city: "Roznov", county: "Neamț" },
  { id: "rosiorii-de-vede", city: "Roșiorii de Vede", county: "Teleorman" },
  { id: "rupea", city: "Rupea", county: "Brașov" },
  { id: "ramnicu-sarat", city: "Râmnicu Sărat", county: "Buzău" },
  { id: "ramnicu-valcea", city: "Râmnicu Vâlcea", county: "Vâlcea" },
  { id: "rasnov", city: "Râșnov", county: "Brașov" },
  { id: "racari", city: "Răcari", county: "Dâmbovița" },
  { id: "radauti", city: "Rădăuți", county: "Suceava" },
  { id: "salcea", city: "Salcea", county: "Suceava" },
  { id: "salonta", city: "Salonta", county: "Bihor" },
  { id: "satu-mare", city: "Satu Mare", county: "Satu Mare" },
  { id: "scornicesti", city: "Scornicești", county: "Olt" },
  { id: "sebes", city: "Sebeș", county: "Alba" },
  { id: "sebis", city: "Sebiș", county: "Arad" },
  { id: "segarcea", city: "Segarcea", county: "Dolj" },
  { id: "seini", city: "Seini", county: "Maramureș" },
  { id: "sfantu-gheorghe", city: "Sfântu Gheorghe", county: "Covasna" },
  { id: "sibiu", city: "Sibiu", county: "Sibiu" },
  { id: "sighetu-marmatiei", city: "Sighetu Marmației", county: "Maramureș" },
  { id: "sighisoara", city: "Sighișoara", county: "Mureș" },
  { id: "simeria", city: "Simeria", county: "Hunedoara" },
  { id: "sinaia", city: "Sinaia", county: "Prahova" },
  { id: "siret", city: "Siret", county: "Suceava" },
  { id: "slatina", city: "Slatina", county: "Olt" },
  { id: "slobozia", city: "Slobozia", county: "Ialomița" },
  { id: "slanic", city: "Slănic", county: "Prahova" },
  { id: "slanic-moldova", city: "Slănic Moldova", county: "Bacău" },
  { id: "solca", city: "Solca", county: "Suceava" },
  { id: "sovata", city: "Sovata", county: "Mureș" },
  { id: "strehaia", city: "Strehaia", county: "Mehedinți" },
  { id: "suceava", city: "Suceava", county: "Suceava" },
  { id: "sulina", city: "Sulina", county: "Tulcea" },
  { id: "sangeorgiu-de-padure", city: "Sângeorgiu de Pădure", county: "Mureș" },
  { id: "sangeorz-bai", city: "Sângeorz-Băi", county: "Bistrița-Năsăud" },
  { id: "sannicolau-mare", city: "Sânnicolau Mare", county: "Timiș" },
  { id: "santana", city: "Sântana", county: "Arad" },
  { id: "sacele", city: "Săcele", county: "Brașov" },
  { id: "sacueni", city: "Săcueni", county: "Bihor" },
  { id: "saliste", city: "Săliște", county: "Sibiu" },
  { id: "salistea-de-sus", city: "Săliștea de Sus", county: "Maramureș" },
  { id: "sarmasu", city: "Sărmașu", county: "Mureș" },
  { id: "saveni", city: "Săveni", county: "Botoșani" },
  { id: "techirghiol", city: "Techirghiol", county: "Constanța" },
  { id: "tecuci", city: "Tecuci", county: "Galați" },
  { id: "teius", city: "Teiuș", county: "Alba" },
  { id: "timisoara", city: "Timișoara", county: "Timiș" },
  { id: "tismana", city: "Tismana", county: "Gorj" },
  { id: "titu", city: "Titu", county: "Dâmbovița" },
  { id: "toplita", city: "Toplița", county: "Harghita" },
  { id: "topoloveni", city: "Topoloveni", county: "Argeș" },
  { id: "tulcea", city: "Tulcea", county: "Tulcea" },
  { id: "turceni", city: "Turceni", county: "Gorj" },
  { id: "turda", city: "Turda", county: "Cluj" },
  { id: "turnu-magurele", city: "Turnu Măgurele", county: "Teleorman" },
  { id: "targoviste", city: "Târgoviște", county: "Dâmbovița" },
  { id: "targu-bujor", city: "Târgu Bujor", county: "Galați" },
  { id: "targu-carbunesti", city: "Târgu Cărbunești", county: "Gorj" },
  { id: "targu-frumos", city: "Târgu Frumos", county: "Iași" },
  { id: "targu-jiu", city: "Târgu Jiu", county: "Gorj" },
  { id: "targu-lapus", city: "Târgu Lăpuș", county: "Maramureș" },
  { id: "targu-mures", city: "Târgu Mureș", county: "Mureș" },
  { id: "targu-neamt", city: "Târgu Neamț", county: "Neamț" },
  { id: "targu-ocna", city: "Târgu Ocna", county: "Bacău" },
  { id: "targu-secuiesc", city: "Târgu Secuiesc", county: "Covasna" },
  { id: "tarnaveni", city: "Târnăveni", county: "Mureș" },
  { id: "talmaciu", city: "Tălmaciu", county: "Sibiu" },
  { id: "tautii-magheraus", city: "Tăuții-Măgherăuș", county: "Maramureș" },
  { id: "tasnad", city: "Tășnad", county: "Satu Mare" },
  { id: "ulmeni", city: "Ulmeni", county: "Maramureș" },
  { id: "ungheni", city: "Ungheni", county: "Mureș" },
  { id: "uricani", city: "Uricani", county: "Hunedoara" },
  { id: "urlati", city: "Urlați", county: "Prahova" },
  { id: "urziceni", city: "Urziceni", county: "Ialomița" },
  { id: "valea-lui-mihai", city: "Valea lui Mihai", county: "Bihor" },
  { id: "vaslui", city: "Vaslui", county: "Vaslui" },
  { id: "vatra-dornei", city: "Vatra Dornei", county: "Suceava" },
  { id: "vascau", city: "Vașcău", county: "Bihor" },
  { id: "vicovu-de-sus", city: "Vicovu de Sus", county: "Suceava" },
  { id: "victoria", city: "Victoria", county: "Brașov" },
  { id: "videle", city: "Videle", county: "Teleorman" },
  { id: "viseu-de-sus", city: "Vișeu de Sus", county: "Maramureș" },
  { id: "vlahita", city: "Vlăhița", county: "Harghita" },
  { id: "voluntari", city: "Voluntari", county: "Ilfov" },
  { id: "vulcan", city: "Vulcan", county: "Hunedoara" },
  { id: "vanju-mare", city: "Vânju Mare", county: "Mehedinți" },
  { id: "valenii-de-munte", city: "Vălenii de Munte", county: "Prahova" },
  { id: "zalau", city: "Zalău", county: "Sălaj" },
  { id: "zimnicea", city: "Zimnicea", county: "Teleorman" },
  { id: "zlatna", city: "Zlatna", county: "Alba" },
  { id: "zarnesti", city: "Zărnești", county: "Brașov" },
  { id: "insuratei", city: "Însurăței", county: "Brăila" },
  { id: "intorsura-buzaului", city: "Întorsura Buzăului", county: "Covasna" },
  { id: "simleu-silvaniei", city: "Șimleu Silvaniei", county: "Sălaj" },
  { id: "somcuta-mare", city: "Șomcuta Mare", county: "Maramureș" },
  { id: "stefanesti", city: "Ștefănești", county: "Argeș" },
  { id: "stefanesti-botosani", city: "Ștefănești", county: "Botoșani" },
  { id: "stei", city: "Ștei", county: "Bihor" },
  { id: "ticleni", city: "Țicleni", county: "Gorj" },
  { id: "tandarei", city: "Țăndărei", county: "Ialomița" },
];
